scaling methods added
mljs/preprocess pull request #2
Opened 2017-03-14 18:17 UTC by jobo322

2017-03-25 02:23 UTC, maasencioh requested changes
This is an old repository, so I'll work on an update of it, but it's important to check first that passes all the tests, that by the way are missing

2017-03-25 02:23 UTC, maasencioh commented on src/pre/scaling.js
> +const Matrix = require('ml-matrix');
first you need to import this package

2017-03-25 02:23 UTC, maasencioh commented on src/pre/scaling.js
> +function centering(dataSet, mean) {
centering it's not exactly a scaling method, so I'll split this one

2017-04-06 16:40 UTC, maasencioh commented
ping @jobo322

2017-04-06 17:00 UTC, jobo322 commented on src/pre/scaling.js
> +function centering(dataSet, mean) {
where can I put it?

2017-04-28 07:34 UTC, lpatiny commented on src/pre/centering.js
> +function centering(dataSet, mean) {
center

2017-04-28 07:34 UTC, lpatiny commented on src/pre/centering.js
> +function centering(dataSet, mean) {
and export it in index.js

2017-04-28 07:35 UTC, lpatiny commented on src/index.js
> +exports.scaling = require('./pre/scaling');
scale

2017-05-02 07:01 UTC, merged